### ISSUE TITLE
API Endpoint calls happening too frequently during search 

### ISSUE THREAD

**Issue by JDubs-55** [JDubs-55/CEN3031_Group111_Project#19]
GetDeck, GetDeckList, and GetAllDecks called too frequently during search. Can refine endpoints and restrict event driven api calls. For example, All three are called when clicking in the search bar. The db search should only occur on initial click, or if something has been typed into the search bar. For getting the deck preview, I think a better endpoint could be created. 

I left console.log messages in the backend.service.ts file to see how often these are occurring.

**Comment by buildmine10** [comment]
A check for if the name list has changed would be a good idea. Then you can check for that before loading the list again.

**Comment by JDubs-55** [comment]
Fixed
